CREATE DATABASE mealdb;

USE mealdb;

CREATE TABLE groups (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE members (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(20) UNIQUE NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    groupID INT NOT NULL,
    FOREIGN KEY (groupID) REFERENCES groups(id) ON DELETE CASCADE
);

CREATE TABLE deposits (
    id INT PRIMARY KEY AUTO_INCREMENT,
    memberID INT NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    depositDate DATE NOT NULL,
    lastDepositAmount DECIMAL(10, 2) NOT NULL,
    addedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    groupID INT NOT NULL,
    FOREIGN KEY (memberID) REFERENCES members(id) ON DELETE CASCADE,
    FOREIGN KEY (groupID) REFERENCES groups(id) ON DELETE CASCADE
);

CREATE TABLE groceries (
    id INT PRIMARY KEY AUTO_INCREMENT,
    groupID INT NOT NULL,
    purchaseDate DATE NOT NULL,
    amount DECIMAL(10, 2) NOT NULL,
    note VARCHAR(255),
    addedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (groupID) REFERENCES groups(id) ON DELETE CASCADE
);

CREATE TABLE meals (
    id INT PRIMARY KEY AUTO_INCREMENT,
    memberID INT NOT NULL,
    mealDate DATE NOT NULL,
    mealCount INT DEFAULT 1,
    groupID INT NOT NULL,
    addedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (memberID) REFERENCES members(id) ON DELETE CASCADE,
    FOREIGN KEY (groupID) REFERENCES groups(id) ON DELETE CASCADE
);