CREATE DATABASE mealdb;

USE mealdb;

CREATE TABLE Groups (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Members (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Phone VARCHAR(20) UNIQUE NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    GroupID INT NOT NULL,
    FOREIGN KEY (GroupID) REFERENCES Groups(ID) ON DELETE CASCADE
);

CREATE TABLE Deposits (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MemberID INT NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    DepositDate DATE NOT NULL,
    DepositDateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
    GroupID INT NOT NULL,
    FOREIGN KEY (MemberID) REFERENCES Members(ID) ON DELETE CASCADE,
    FOREIGN KEY (GroupID) REFERENCES Groups(ID) ON DELETE CASCADE
);

CREATE TABLE Groceries (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    GroupID INT NOT NULL,
    PurchaseDate DATE NOT NULL,
    Amount DECIMAL(10, 2) NOT NULL,
    Note VARCHAR(255),
    AddedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (GroupID) REFERENCES Groups(ID) ON DELETE CASCADE
);

CREATE TABLE Meals (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MemberID INT NOT NULL,
    MealDate DATE NOT NULL,
    MealCount INT DEFAULT 1,
    GroupID INT NOT NULL,
    FOREIGN KEY (MemberID) REFERENCES Members(ID) ON DELETE CASCADE,
    FOREIGN KEY (GroupID) REFERENCES Groups(ID) ON DELETE CASCADE
);

-- Insert a sample group (password: admin123)
INSERT INTO Groups (Name, Password) VALUES ('Engineers-Home', 'admin123');

-- Insert sample members
INSERT INTO Members (Name, Phone, GroupID) VALUES 
('Ajmain', '0123456789', 1),
('Nobel', '0123456790', 1),
('Siddik', '0123456791', 1),
('Sabbir', '0123456792', 1),
('Faisal', '0123456793', 1);